// <auto-generated />
using System;
using Filipan_Dănuț_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Filipan_Dănuț_Proiect.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Drink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Liters")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Drink");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("DrinkID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("DrinkID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.ProvidedDrink", b =>
                {
                    b.Property<int>("DrinkID")
                        .HasColumnType("int");

                    b.Property<int>("ProviderID")
                        .HasColumnType("int");

                    b.HasKey("DrinkID", "ProviderID");

                    b.HasIndex("ProviderID");

                    b.ToTable("ProvidedDrink");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Provider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Site")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("provider");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Order", b =>
                {
                    b.HasOne("Filipan_Dănuț_Proiect.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filipan_Dănuț_Proiect.Models.Drink", "Drink")
                        .WithMany("Orders")
                        .HasForeignKey("DrinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.ProvidedDrink", b =>
                {
                    b.HasOne("Filipan_Dănuț_Proiect.Models.Drink", "Drink")
                        .WithMany("ProvidedDrinks")
                        .HasForeignKey("DrinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filipan_Dănuț_Proiect.Models.Provider", "Provider")
                        .WithMany("ProvidedDrinks")
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Drink", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProvidedDrinks");
                });

            modelBuilder.Entity("Filipan_Dănuț_Proiect.Models.Provider", b =>
                {
                    b.Navigation("ProvidedDrinks");
                });
#pragma warning restore 612, 618
        }
    }
}
